[package]
name = "generator"
version = "0.1.0"
edition = "2021"

[dependencies]
tera = { workspace = true}

primitive-types = { workspace = true }
structure = { workspace = true }
registry = { workspace = true }
parser = { workspace = true }